# Generated by Django 4.0.4 on 2022-05-09 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='عنوان')),
                ('body', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('action_link', models.CharField(blank=True, max_length=255, null=True, verbose_name='لینک عملیات')),
                ('alert_type', models.CharField(choices=[('info', 'اطلاعات'), ('success', 'موفقیت'), ('warning', 'توجه'), ('danger', 'اخطار')], default='info', max_length=10, verbose_name='نوع')),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'هشدار',
                'verbose_name_plural': 'هشدار',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150, verbose_name='نام')),
            ],
            options={
                'verbose_name': 'شغل',
                'verbose_name_plural': 'شغل',
            },
        ),
        migrations.CreateModel(
            name='CareerGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150, verbose_name='نام')),
            ],
            options={
                'verbose_name': 'گروه شغلی',
                'verbose_name_plural': 'گروه شغلی',
            },
        ),
        migrations.CreateModel(
            name='UserAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seen_datetime', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ دیده شدن')),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_alerts', to='core.alert', verbose_name='هشدار')),
            ],
            options={
                'verbose_name': 'هشدار کاربر',
                'verbose_name_plural': 'هشدار کاربر',
                'ordering': ('-created_at',),
            },
        ),
    ]
