# Generated by Django 4.0.4 on 2022-05-09 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='current_medicines',
        ),
        migrations.AddField(
            model_name='user',
            name='current_medicines',
            field=models.TextField(blank=True, null=True, verbose_name='داروهای مصرفی فعلی'),
        ),
    ]
