# Generated by Django 4.0.4 on 2022-05-30 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_current_medicines_user_current_medicines'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='marriage_status',
            field=models.IntegerField(blank=True, choices=[(0, 'مجرد'), (1, 'متاهل')], default=0, null=True, verbose_name='وضعیت تاهل'),
        ),
    ]
