# Generated by Django 4.1.1 on 2022-09-17 18:29

import apps.users.models
import apps.users.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthSMSRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mobile', models.CharField(help_text='مثلا 09123456789', max_length=11, validators=[apps.users.validators.MobileValidator()], verbose_name='موبایل')),
                ('sms_code', models.CharField(blank=True, max_length=5, null=True, verbose_name='کد پیامکی')),
                ('expire_datetime', models.DateTimeField(default=apps.users.models.onehour_from_now)),
                ('request_status', models.CharField(choices=[('pending', 'در انتظار'), ('completed', 'پایان یافته')], default='pending', max_length=10)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
            ],
            options={
                'verbose_name': 'درخواست احراز هویت پیامکی',
                'verbose_name_plural': 'درخواست احراز هویت پیامکی',
                'ordering': ('-id',),
            },
        ),
    ]
