# Generated by Django 4.0.4 on 2022-05-09 18:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinic', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to=settings.AUTH_USER_MODEL, verbose_name='بیمار'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='requested_services',
            field=models.ManyToManyField(related_name='reservations', to='clinic.service', verbose_name='خدمات درخواستی'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_reservations', to=settings.AUTH_USER_MODEL, verbose_name='منشی'),
        ),
        migrations.AddField(
            model_name='imagegallery',
            name='reservation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clinic.reservation', verbose_name='رزرو'),
        ),
        migrations.AddField(
            model_name='imagegallery',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AddField(
            model_name='brand',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='brands', to='clinic.brandcompany', verbose_name='شرکت'),
        ),
        migrations.AlterUniqueTogether(
            name='booktime',
            unique_together={('date', 'time_in_day')},
        ),
    ]
