# Generated by Django 4.0.4 on 2022-05-09 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'verbose_name': 'نام برند', 'verbose_name_plural': 'نام برند'},
        ),
    ]
