# Generated by Django 4.0.5 on 2022-06-10 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0004_booktime_locked'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booktime',
            options={'ordering': ('time_in_day',), 'verbose_name': 'زمان رزرو', 'verbose_name_plural': 'زمان رزرو'},
        ),
    ]
