# Generated by Django 4.0.5 on 2022-06-19 09:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clinic', '0005_alter_booktime_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservationservice',
            old_name='service_amount',
            new_name='amount',
        ),
        migrations.RemoveField(
            model_name='reservationservice',
            name='service_brand',
        ),
        migrations.AddField(
            model_name='brand',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات'),
        ),
        migrations.AddField(
            model_name='brandcompany',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات'),
        ),
        migrations.AddField(
            model_name='medicine',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='medicines', to='clinic.brand', verbose_name='برند'),
        ),
        migrations.AlterField(
            model_name='imagegallery',
            name='reservation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='images', to='clinic.reservation', verbose_name='رزرو'),
        ),
        migrations.AlterField(
            model_name='imagegallery',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='images', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.IntegerField(default=0, verbose_name='قیمت (تومان)'),
        ),
    ]
