# Generated by Django 4.1.1 on 2022-11-06 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0007_alter_brand_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('before_photo', models.ImageField(upload_to='gallery/', verbose_name='عکس قبل')),
                ('after_photo', models.ImageField(blank=True, null=True, upload_to='gallery/', verbose_name='عکس بعد')),
                ('full_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='نام و نام خانوادگی')),
                ('start_time', models.DateTimeField(verbose_name='شروع درمان')),
                ('end_time', models.DateTimeField(verbose_name='پایان درمان')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='نظر بیمار')),
                ('is_published', models.BooleanField(default=False, verbose_name='منتشر شده')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد شده در')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='ویرایش شده در')),
                ('service_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.service', verbose_name='نام خدمت')),
            ],
            options={
                'verbose_name': 'نمونه کار',
                'verbose_name_plural': 'نمونه کار',
            },
        ),
    ]
